### PR TITLE
Upgrade to rc10, make repo `nuxi init` friendly

### LINKED ISSUE #33: Upgrade to nuxt RC10
### Describe the feature

RC10 was released https://github.com/nuxt/framework/discussions/7513 🎊 

We should:
- [x] upgrade to RC.10
- [x] flatten the repo, remove `app/`
- [x] register our template with https://github.com/unjs/giget#template-registry
- [ ] update our docs to use `nuxi init` as the starting command

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by BracketJohn**
Closes #33.

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [ ] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

### CODE REVIEW

**Review by zoey-kaiser — APPROVED** [review]
LGTM! Awesome to see how quickly we are adapting to new NUXT Versions! Also really like the changes to the ReadMe. It should make the start much easier for developers!

**Comment by BracketJohn** [comment]
> Do we still want to take care of registering our template with https://github.com/unjs/giget#template-registry or do we push this back into a new issue?

Into a new PR, I already have this prepared but want to ensure that the repo is ready first and then do a second, small PR that just updated the documentation.

**Comment by zoey-kaiser** [comment]
I like the new badges! Do you also one to add one for the website (https://sidebase.io)?

**Comment by BracketJohn** [comment]
It's already linked higher up in the sidebar, I think for now that's enough!

**Comment by zoey-kaiser** [comment]
Perfect! Then I think we are ready for merge!

**Review by zoey-kaiser — APPROVED** [review]

**Pull request merged**
